### PR TITLE
RTL support for konsta UI

### PR DESCRIPTION
**Pull request by ibilux**
Add support for multi-directional layouts for `Konsta UI` with tailwind `rtl` and `ltr` modifiers. 
Trying to fix this issue #104.
A complete example can be found here:
[https://github.com/ibilux/konsta-svelte-rtl](https://github.com/ibilux/konsta-svelte-rtl)

This PR is tested with the components showing the pictures below:
| LTR | RTL |
| :---: | :---: |
| LTR |  RTL |

### CODE REVIEW

**Comment by ibilux** [comment]
A link to the preview:
[https://ibilux-didactic-waddle-46jg4p67xxfq4x6-5173.preview.app.github.dev/](https://ibilux-didactic-waddle-46jg4p67xxfq4x6-5173.preview.app.github.dev/)

**Comment by ibilux** [comment]
@nolimits4web tailwind marked `rtl` and `ltr` variants as stable in [v3.3.0](https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.3.0).

**Comment by vltansky** [comment]
@ibilux why not to use logical properties?
https://tailwindcss.com/blog/tailwindcss-v3-3#simplified-rtl-support-with-logical-properties

**Comment by vltansky** [comment]
@ibilux why not to use logical properties instead of rtl/ltr?

easier to maintain and solid browser support. 

https://tailwindcss.com/blog/tailwindcss-v3-3#simplified-rtl-support-with-logical-properties

**Comment by ibilux** [comment]
@vltansky Yes, you are right. And I started testing them yesterday.
But as you can see the link you shared is posted in `Tuesday, March 28, 2023`, and it's before I started this PR.

**Comment by ibilux** [comment]
@nolimits4web I have changed the code to use logical properties for inline direction instead of modifiers.
Everything seems to be working.
Please re-check the [plugin-safe-areas.js](https://github.com/konstaui/konsta/pull/133/files#diff-e73f8ac6feed2438ae10b600f556612114e4b97591e4bde2cf25cd69b853a44b) file, cause I'm not sure if I did it right.

**Comment by nolimits4web** [comment]
Thanks @ibilux, will check it on a days!

**Pull request merged**
